{
 "title": "Example baton nagimator",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "metrics", "query": "prometheus" },
   {
    "name": "host",
    "query": "label_values(go_info{}, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Кнопочный РПС",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(buttoners_example_baton_nagimator_button_lovers_total{instance=~\"$host\", service_name=\"example-button-nagimator\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "Главные часовые нажиматоры",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(delta(buttoners_example_baton_nagimator_button_lovers_total{instance=~\"$host\", service_name=\"example-button-nagimator\"}[1h])) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Я кушаю",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(go_memstats_sys_bytes{instance=~\"$host\", service_name=\"example-button-nagimator\"})"
    }
   ]
  }
 ]
}